development:
  facebook_key: "452410698112385"
  facebook_secret: "f6c41e771aec0968b36c7fdfb49fbd12"

  twitter_key: "Bdyx2U1waoNMEXn78nGdd14t2"
  twitter_secret: "0YPMNPd7V4p36Zzj5xzBfweVqPS4IhOdlE99Txun1eW2giGO6C"
  twitter_token: "168429845-anokGzKl2dUM4iTpN44KfTpVmtvZGQlJMUt6hqZT"
  twitter_token_secret: "gQEWaSpTfRtvWdXwhqCXzsiKZYTihIh23j0skbo5tzT73"

  github_key: "YOUR_KEY"
  github_secret: "YOUR_SECRET"

  linkedin_key: "YOUR_KEY"
  linkedin_secret: "YOUR_SECRET"

  google_key: "YOUR_KEY"
  google_secret: "YOUR_SECRET"

  GMAIL_DOMAIN: "thawing-lake-7709.herokuapp.com"
  GMAIL_USERNAME: "support@chronicdiseases.org.uk"
  GMAIL_PASSWORD: "22CHaberek22"


production:
  facebook_key: "452410698112385"
  facebook_secret: "f6c41e771aec0968b36c7fdfb49fbd12"

  twitter_key: "Bdyx2U1waoNMEXn78nGdd14t2"
  twitter_secret: "0YPMNPd7V4p36Zzj5xzBfweVqPS4IhOdlE99Txun1eW2giGO6C"
  twitter_token: "168429845-anokGzKl2dUM4iTpN44KfTpVmtvZGQlJMUt6hqZT"
  twitter_token_secret: "gQEWaSpTfRtvWdXwhqCXzsiKZYTihIh23j0skbo5tzT73"

  github_key: "YOUR_KEY"
  github_secret: "YOUR_SECRET"

  linkedin_key: "YOUR_KEY"
  linkedin_secret: "YOUR_SECRET"

  google_key: "YOUR_KEY"
  google_secret: "YOUR_SECRET"

  GMAIL_DOMAIN: "thawing-lake-7709.herokuapp.com"
  GMAIL_USERNAME: "support@chronicdiseases.org.uk"
  GMAIL_PASSWORD: "22CHaberek22"

  AWS_BUCKET: "chroncop"
  s3_host_name: "s3-eu-west-1.amazonaws.com"
  AWS_KEY: "AKIAJTIBP6BX2AL6JSXQ"
  AWS_SECRET: "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"