development:
  facebook_key: ""
  facebook_secret: ""

  twitter_key: ""
  twitter_secret: ""
  twitter_token: ""
  twitter_token_secret: ""

  github_key: "YOUR_KEY"
  github_secret: "YOUR_SECRET"

  linkedin_key: "YOUR_KEY"
  linkedin_secret: "YOUR_SECRET"

  google_key: "YOUR_KEY"
  google_secret: "YOUR_SECRET"

  GMAIL_DOMAIN: "thawing-lake-7709.herokuapp.com"
  GMAIL_USERNAME: "support@chronicdiseases.org.uk"
  GMAIL_PASSWORD: ""


production:
  facebook_key: ""
  facebook_secret: ""

  twitter_key: ""
  twitter_secret: ""
  twitter_token: ""
  twitter_token_secret: ""

  github_key: "YOUR_KEY"
  github_secret: "YOUR_SECRET"

  linkedin_key: "YOUR_KEY"
  linkedin_secret: "YOUR_SECRET"

  google_key: "YOUR_KEY"
  google_secret: "YOUR_SECRET"

  GMAIL_DOMAIN: "thawing-lake-7709.herokuapp.com"
  GMAIL_USERNAME: "support@chronicdiseases.org.uk"
  GMAIL_PASSWORD: ""
