development:
  facebook_key: "452410698112385"
  facebook_secret: "f6c41e771aec0968b36c7fdfb49fbd12"

  twitter_key: "Bdyx2U1waoNMEXn78nGdd14t2"
  twitter_secret: "0YPMNPd7V4p36Zzj5xzBfweVqPS4IhOdlE99Txun1eW2giGO6C"

  github_key: "YOUR_KEY"
  github_secret: "YOUR_SECRET"

  linkedin_key: "YOUR_KEY"
  linkedin_secret: "YOUR_SECRET"

  google_key: "YOUR_KEY"
  google_secret: "YOUR_SECRET"

  GMAIL_DOMAIN: "chronicdiseases.org.uk"
  GMAIL_USERNAME: "support@chronicdiseases.org.uk"
  GMAIL_PASSWORD: "22chaberek22"


production:
  facebook_key: "452410698112385"
  facebook_secret: "f6c41e771aec0968b36c7fdfb49fbd12"

  twitter_key: "Bdyx2U1waoNMEXn78nGdd14t2"
  twitter_secret: "0YPMNPd7V4p36Zzj5xzBfweVqPS4IhOdlE99Txun1eW2giGO6C"

  github_key: "YOUR_KEY"
  github_secret: "YOUR_SECRET"

  linkedin_key: "YOUR_KEY"
  linkedin_secret: "YOUR_SECRET"

  google_key: "YOUR_KEY"
  google_secret: "YOUR_SECRET"

  GMAIL_DOMAIN: "thawing-lake-7709.herokuapp.com"
  GMAIL_USERNAME: "support@chronicdiseases.org.uk"
  GMAIL_PASSWORD: "22chaberek22"
